import { useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { router } from 'expo-router';
import { ScreenContainer } from '@/components/screen-container';
import { BilateralMark, Card, DS, PrimaryButton } from '@/components/ui/design-system';
import { createTrace } from '@/lib/ai-contracts';
import { evaluateAIPolicy } from '@/lib/ai-policy';

export default function AILabScreen() { const [consent, setConsent] = useState(false); const [assigned, setAssigned] = useState(false); const [activated, setActivated] = useState(false); const result = useMemo(() => evaluateAIPolicy({ consentGiven: consent, therapistAssigned: assigned, activatedByTrainee: activated, fatigue: 0, overrideRequested: false, traumaReprocessingAllowed: false }), [consent, assigned, activated]); const trace = createTrace('ai-lab-self-check', 'local-heuristic', ['policy-gates']); return <ScreenContainer containerClassName="bg-[#F4F7F5]" className="px-5 pt-4"><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><View><Text style={styles.eyebrow}>AI LAB</Text><Text style={styles.heading}>Test the gates.{`\n`}Keep humans in review.</Text></View><BilateralMark size={44} /></View><View style={styles.boundary}><Text style={styles.boundaryTitle}>Local self-check only</Text><Text style={styles.boundaryBody}>No provider call is made. This screen exercises bounded policy logic and produces a review-required trace.</Text></View><Card><Gate title="Applicable consent" value={consent} onChange={setConsent} /><View style={styles.divider}/><Gate title="Therapist assigned" value={assigned} onChange={setAssigned} /><View style={styles.divider}/><Gate title="Feature activated by trainee" value={activated} onChange={setActivated} /></Card><Card tint={result.allowed ? DS.mint : '#FFF7E9'}><Text style={styles.status}>{result.allowed ? 'GATE PASSED · REVIEW REQUIRED' : 'GATE BLOCKED'}</Text><Text style={styles.result}>{result.reason}</Text><Text style={styles.trace}>Trace {trace.traceId} · {trace.provider}</Text></Card><PrimaryButton onPress={() => router.push('/supervisor')}>Open supervisor cues</PrimaryButton><Pressable accessibilityRole="button" onPress={() => router.back()}><Text style={styles.back}>Return</Text></Pressable></ScrollView></ScreenContainer>; }
function Gate({ title, value, onChange }: { title: string; value: boolean; onChange: (value: boolean) => void }) { return <View style={styles.gate}><Text style={styles.gateTitle}>{title}</Text><Switch accessibilityLabel={title} value={value} onValueChange={onChange} trackColor={{ false: '#CBD7D3', true: '#8FC8BC' }} thumbColor="#FFFFFF" /></View>; }
const styles = StyleSheet.create({ content: { paddingBottom: 40, gap: 13 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' }, eyebrow: { color: DS.deep, fontSize: 12, letterSpacing: 1.4, fontWeight: '700', marginTop: 4 }, heading: { color: DS.ink, fontSize: 30, lineHeight: 36, fontWeight: '700', marginTop: 6 }, boundary: { backgroundColor: DS.lavender, borderRadius: 16, padding: 14 }, boundaryTitle: { color: DS.ink, fontSize: 14, fontWeight: '800', marginBottom: 4 }, boundaryBody: { color: DS.muted, fontSize: 12, lineHeight: 18 }, gate: { minHeight: 56, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, gateTitle: { color: DS.ink, fontSize: 13, fontWeight: '700' }, divider: { height: 1, backgroundColor: DS.line }, status: { color: DS.deep, fontSize: 10, letterSpacing: 1, fontWeight: '800', marginBottom: 7 }, result: { color: DS.ink, fontSize: 14, lineHeight: 20 }, trace: { color: DS.muted, fontSize: 10, marginTop: 10 }, back: { color: DS.deep, fontWeight: '800', textAlign: 'center', padding: 8 } });
