import { useState } from 'react';
import { router } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { ScreenContainer } from '@/components/screen-container';
import { BilateralMark, Card, DS, PrimaryButton } from '@/components/ui/design-system';
import { usePreferences } from '@/lib/preferences-context';

const steps = [
  { eyebrow: 'WELCOME', title: 'A steadier moment starts here.', body: 'This is a private, supportive space for noticing what is happening now. You choose the pace and you can leave at any time.' },
  { eyebrow: 'YOU ARE IN CONTROL', title: 'Pause or stop whenever you need.', body: 'The visual dot, audio cues, and haptics are optional. Use grounding instead if you feel overwhelmed, disconnected, or unsafe.' },
  { eyebrow: 'PRIVATE BY DEFAULT', title: 'Your reflections stay on this device.', body: 'This prototype does not require an account or send your journal entries to the cloud. Sharing with a therapist is not enabled.' },
];
export default function OnboardingScreen() { const [step, setStep] = useState(0); const { completeOnboarding } = usePreferences(); const current = steps[step]; const next = () => step === steps.length - 1 ? (completeOnboarding(), router.replace('/(tabs)')) : setStep((v) => v + 1); return <ScreenContainer edges={['top','bottom','left','right']} containerClassName="bg-[#F4F7F5]" className="px-5 pt-6"><View style={styles.content}><View style={styles.brand}><BilateralMark size={64} /><Text style={styles.brandName}>EMDR THERAPY</Text></View><View style={styles.hero}><Text style={styles.eyebrow}>{current.eyebrow}</Text><Text style={styles.heading}>{current.title}</Text><Text style={styles.body}>{current.body}</Text></View><Card tint={step === 1 ? DS.lavender : DS.mint}><Text style={styles.cardTitle}>{step === 0 ? 'No right way to begin' : step === 1 ? 'Gentle is enough' : 'You decide what is shared'}</Text><Text style={styles.cardBody}>{step === 0 ? 'Start with a grounding exercise, a short check-in, or simply look around the room.' : step === 1 ? 'Therapy tools support care; they do not replace a qualified therapist or emergency support.' : 'Keep details broad. You never need to disclose trauma content to use the calming tools.'}</Text></Card><View style={styles.dots}>{steps.map((_, index) => <View key={index} style={[styles.dot, index === step && styles.dotActive]} />)}</View><PrimaryButton onPress={next}>{step === steps.length - 1 ? 'Enter your space' : 'Continue'}</PrimaryButton><Pressable onPress={() => router.replace('/(tabs)')}><Text style={styles.skip}>Skip for now</Text></Pressable></View></ScreenContainer>; }
const styles = StyleSheet.create({ content: { flex: 1, paddingBottom: 22, justifyContent: 'space-between' }, brand: { alignItems: 'center', gap: 10, marginTop: 12 }, brandName: { color: DS.deep, fontSize: 12, letterSpacing: 1.6, fontWeight: '800' }, hero: { alignItems: 'center', gap: 12, paddingHorizontal: 8 }, eyebrow: { color: DS.deep, fontSize: 12, letterSpacing: 1.5, fontWeight: '700' }, heading: { color: DS.ink, fontSize: 31, lineHeight: 37, fontWeight: '700', textAlign: 'center' }, body: { color: DS.muted, fontSize: 15, lineHeight: 22, textAlign: 'center' }, cardTitle: { color: DS.ink, fontSize: 15, fontWeight: '800', marginBottom: 6 }, cardBody: { color: DS.muted, fontSize: 13, lineHeight: 19 }, dots: { flexDirection: 'row', justifyContent: 'center', gap: 7, marginVertical: 8 }, dot: { width: 7, height: 7, borderRadius: 4, backgroundColor: DS.aqua }, dotActive: { width: 22, backgroundColor: DS.deep }, skip: { color: DS.muted, textAlign: 'center', fontSize: 13, fontWeight: '700', padding: 8 } });
