import { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { ScreenContainer } from '@/components/screen-container';
import { BilateralMark, Card, DS } from '@/components/ui/design-system';
import { haptic } from '@/lib/haptics';

const resources = [{ id: 'orient', title: 'Orient to the room', duration: '2 minutes', tint: DS.mint, steps: ['Feel both feet supported.', 'Name five things you can see.', 'Name one sound close to you.', 'Let your eyes rest on a neutral object.'] }, { id: 'breath', title: 'Longer exhale', duration: '1 minute', tint: DS.lavender, steps: ['Breathe in gently for a count of 3.', 'Breathe out slowly for a count of 5.', 'Repeat only while it feels comfortable.', 'Return to a natural breath.'] }, { id: 'senses', title: 'Five gentle senses', duration: '3 minutes', tint: '#FFF7E9', steps: ['Notice one color you like.', 'Feel one point of contact with a surface.', 'Notice the temperature of the air.', 'Choose one small sound to follow.'] }];
export default function ResourcesScreen() { const [active, setActive] = useState<string | null>(null); const selected = resources.find((resource) => resource.id === active); return <ScreenContainer containerClassName="bg-[#F4F7F5]" className="px-5 pt-4"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><View style={styles.header}><View><Text style={styles.eyebrow}>GROUNDING LIBRARY</Text><Text style={styles.heading}>Come back to now.</Text></View><BilateralMark size={44} /></View><Text style={styles.sub}>Choose a short, optional exercise. Nothing needs to be forced, completed, or interpreted.</Text><Text style={styles.reviewed}>Foundational exercises only · review with a qualified therapist before using them alongside trauma processing.</Text>{selected ? <Card tint={selected.tint}><Text style={styles.activeTitle}>{selected.title}</Text><Text style={styles.activeDuration}>{selected.duration}</Text><View style={styles.steps}>{selected.steps.map((step, index) => <View key={step} style={styles.step}><Text style={styles.stepNumber}>{index + 1}</Text><Text style={styles.stepText}>{step}</Text></View>)}</View><Pressable onPress={() => { haptic.light(); setActive(null); }} style={styles.done}><Text style={styles.doneText}>Return to exercises</Text></Pressable></Card> : resources.map((resource) => <Pressable key={resource.id} onPress={() => { haptic.light(); if (resource.id === 'breath') { router.push('/breathing'); } else { setActive(resource.id); } }} style={[styles.resource, { backgroundColor: resource.tint }]}><View style={styles.resourceMark}><BilateralMark size={28} /></View><View style={{ flex: 1 }}><Text style={styles.resourceTitle}>{resource.title}</Text><Text style={styles.resourceBody}>{resource.duration} · gentle sensory reset</Text></View><Text style={styles.chevron}>›</Text></Pressable>)}<View style={styles.safety}><Text style={styles.safetyTitle}>A note on safety</Text><Text style={styles.safetyBody}>Stop if anything feels uncomfortable. If you feel unsafe or may hurt yourself or someone else, use crisis resources or contact local emergency services.</Text></View><Pressable onPress={() => router.back()}><Text style={styles.back}>Return</Text></Pressable></ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ content: { paddingBottom: 40, gap: 13 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' }, eyebrow: { color: DS.deep, fontSize: 12, letterSpacing: 1.4, fontWeight: '700', marginTop: 4 }, heading: { color: DS.ink, fontSize: 31, lineHeight: 37, fontWeight: '700', marginTop: 6 }, sub: { color: DS.muted, fontSize: 14, lineHeight: 21, marginBottom: 3 }, reviewed: { color: DS.deep, fontSize: 11, lineHeight: 16, marginBottom: 2 }, resource: { borderRadius: 18, padding: 14, flexDirection: 'row', alignItems: 'center', gap: 12, borderWidth: 1, borderColor: DS.line }, resourceMark: { width: 40, height: 40, borderRadius: 14, backgroundColor: DS.surface, justifyContent: 'center', alignItems: 'center' }, resourceTitle: { color: DS.ink, fontSize: 15, fontWeight: '800', marginBottom: 3 }, resourceBody: { color: DS.muted, fontSize: 12 }, chevron: { color: DS.muted, fontSize: 25 }, activeTitle: { color: DS.ink, fontSize: 21, fontWeight: '800' }, activeDuration: { color: DS.deep, fontSize: 12, fontWeight: '700', marginTop: 4 }, steps: { gap: 12, marginTop: 18 }, step: { flexDirection: 'row', alignItems: 'center', gap: 10 }, stepNumber: { width: 25, height: 25, borderRadius: 13, backgroundColor: DS.surface, color: DS.deep, textAlign: 'center', paddingTop: 4, fontWeight: '800' }, stepText: { color: DS.ink, fontSize: 14, flex: 1 }, done: { borderWidth: 1, borderColor: DS.deep, borderRadius: 12, paddingVertical: 11, alignItems: 'center', marginTop: 18 }, doneText: { color: DS.deep, fontSize: 13, fontWeight: '800' }, safety: { backgroundColor: '#FFF7E9', borderRadius: 16, padding: 14 }, safetyTitle: { color: DS.ink, fontSize: 13, fontWeight: '800', marginBottom: 4 }, safetyBody: { color: '#776345', fontSize: 12, lineHeight: 18 }, back: { color: DS.muted, textAlign: 'center', padding: 8, fontWeight: '700' } });
