import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { ScreenContainer } from '@/components/screen-container';
import { BilateralMark, Card, DS } from '@/components/ui/design-system';
import { EMDR_PHASES, TRAINING_BOUNDARY, type SupervisorCue } from '@/lib/training-model';

const cues: SupervisorCue[] = [
  { id: 'prep', phase: 'Preparation', title: 'Check readiness before moving on', teachingCue: 'Invite the trainee to confirm that the simulated patient can return to a chosen safe-place image.', severity: 'observe' },
  { id: 'sud', phase: 'Desensitization', title: 'Pause and assess the signal', teachingCue: 'If simulated SUD remains high, slow down and use therapist judgment rather than increasing stimulation.', severity: 'pause' },
  { id: 'close', phase: 'Closure', title: 'Close the set with orientation', teachingCue: 'Practice returning attention to the room and documenting what the simulated patient reports.', severity: 'observe' },
];

export default function SupervisorScreen() { return <ScreenContainer containerClassName="bg-[#F4F7F5]" className="px-5 pt-4"><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><View><Text style={styles.eyebrow}>TRAINING SUPERVISOR</Text><Text style={styles.heading}>Notice. Reflect.{`\n`}Stay within scope.</Text></View><BilateralMark size={44} /></View><View style={styles.boundary}><Text style={styles.boundaryTitle}>Training simulator only</Text><Text style={styles.boundaryBody}>{TRAINING_BOUNDARY}</Text></View><Card><Text style={styles.cardTitle}>Eight-phase map</Text><View style={styles.phaseGrid}>{EMDR_PHASES.map((phase, index) => <View key={phase} style={styles.phase}><Text style={styles.phaseNumber}>{index + 1}</Text><Text style={styles.phaseText}>{phase}</Text></View>)}</View></Card><Text style={styles.section}>Teaching cues</Text>{cues.map((cue) => <Card key={cue.id} tint={cue.severity === 'pause' ? '#FFF7E9' : DS.mint}><Text style={styles.cueMeta}>{cue.phase} · {cue.severity === 'pause' ? 'PAUSE & REVIEW' : 'OBSERVE'}</Text><Text style={styles.cueTitle}>{cue.title}</Text><Text style={styles.cueBody}>{cue.teachingCue}</Text></Card>)}<Text style={styles.footer}>Simulated supervisor cues are heuristic educational prompts. They are not clinical instructions, diagnosis, or autonomous therapy.</Text><Pressable accessibilityRole="button" onPress={() => router.back()}><Text style={styles.back}>Return</Text></Pressable></ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ content: { paddingBottom: 40, gap: 13 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' }, eyebrow: { color: DS.deep, fontSize: 12, letterSpacing: 1.4, fontWeight: '700', marginTop: 4 }, heading: { color: DS.ink, fontSize: 30, lineHeight: 36, fontWeight: '700', marginTop: 6 }, boundary: { backgroundColor: DS.lavender, borderRadius: 16, padding: 14 }, boundaryTitle: { color: DS.ink, fontSize: 14, fontWeight: '800', marginBottom: 4 }, boundaryBody: { color: DS.muted, fontSize: 12, lineHeight: 18 }, cardTitle: { color: DS.ink, fontSize: 16, fontWeight: '800', marginBottom: 10 }, phaseGrid: { gap: 9 }, phase: { flexDirection: 'row', alignItems: 'center', gap: 9 }, phaseNumber: { width: 22, height: 22, borderRadius: 11, backgroundColor: DS.deep, color: '#FFFFFF', textAlign: 'center', paddingTop: 3, fontSize: 11, fontWeight: '800' }, phaseText: { color: DS.ink, fontSize: 13 }, section: { color: DS.ink, fontSize: 18, fontWeight: '800', marginTop: 4 }, cueMeta: { color: DS.deep, fontSize: 10, letterSpacing: 1, fontWeight: '800', marginBottom: 5 }, cueTitle: { color: DS.ink, fontSize: 15, fontWeight: '800', marginBottom: 4 }, cueBody: { color: DS.muted, fontSize: 12, lineHeight: 18 }, footer: { color: DS.muted, fontSize: 11, lineHeight: 16, textAlign: 'center', marginTop: 5 }, back: { color: DS.deep, fontWeight: '800', textAlign: 'center', padding: 8 } });
