import React from 'react';
import { router, useLocalSearchParams } from 'expo-router';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { ScreenContainer } from '@/components/screen-container';
import { SessionWizardProgress } from '@/components/session-wizard-progress';
import { haptic } from '@/lib/haptics';
import { carrySessionParams, type SessionFlowParams } from '@/lib/session-flow';
export default function AssessmentScreen() { const params = useLocalSearchParams<SessionFlowParams>(); const [sud, setSud] = React.useState(6); const sessionParams = carrySessionParams({ ...params, sud: String(sud) }); return <ScreenContainer containerClassName="bg-[#F4F7F5]" className="px-5 pt-4"><View style={styles.content}><SessionWizardProgress active={1} /><Text style={styles.eyebrow}>PHASE 3 · ASSESSMENT</Text><Text style={styles.heading}>Name only what feels manageable.</Text><Text style={styles.body}>You can keep details broad. This prototype does not send your notes anywhere.</Text><Text style={styles.label}>A brief image or focus</Text><TextInput placeholder="Optional — a few words" placeholderTextColor="#9AA9A5" style={styles.input} /><Text style={styles.label}>A belief that feels difficult right now</Text><TextInput placeholder="Optional — for example, “I’m not safe”" placeholderTextColor="#9AA9A5" style={styles.input} /><Text style={styles.label}>Current SUD level: {sud}/10</Text><View style={styles.scale}>{Array.from({ length: 11 }, (_, i) => <Pressable key={i} onPress={() => { haptic.light(); setSud(i); }} style={[styles.scaleDot, i === sud && styles.scaleSelected]}><Text style={[styles.scaleText, i === sud && styles.scaleTextSelected]}>{i}</Text></Pressable>)}</View><View style={styles.note}><Text style={styles.noteText}>If your number rises sharply or you feel unsafe, stop and use grounding instead.</Text></View><Pressable onPress={() => { haptic.light(); router.push({ pathname: '/session/bls', params: sessionParams as Record<string, string> }); }} style={styles.button}><Text style={styles.buttonText}>Start one gentle set</Text></Pressable></View></ScreenContainer>; }
const styles = StyleSheet.create({ content: { gap: 12 }, eyebrow: { color: '#2F6F68', fontSize: 12, letterSpacing: 1.4, fontWeight: '700', marginTop: 4 }, heading: { color: '#16252D', fontSize: 29, lineHeight: 35, fontWeight: '700' }, body: { color: '#60716F', fontSize: 14, lineHeight: 21, marginBottom: 8 }, label: { color: '#16252D', fontSize: 14, fontWeight: '700', marginTop: 4 }, input: { backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#D9E2DE', borderRadius: 14, paddingHorizontal: 14, paddingVertical: 14, color: '#16252D', fontSize: 14 }, scale: { flexDirection: 'row', justifyContent: 'space-between', backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#D9E2DE', borderRadius: 16, padding: 10 }, scaleDot: { width: 25, height: 25, alignItems: 'center', justifyContent: 'center', borderRadius: 13 }, scaleSelected: { backgroundColor: '#2F6F68' }, scaleText: { color: '#60716F', fontSize: 12 }, scaleTextSelected: { color: '#FFFFFF', fontWeight: '700' }, note: { backgroundColor: '#FFF7E9', borderRadius: 14, padding: 13, marginTop: 4 }, noteText: { color: '#776345', fontSize: 12, lineHeight: 17 }, button: { backgroundColor: '#2F6F68', alignItems: 'center', borderRadius: 15, paddingVertical: 16, marginTop: 8 }, buttonText: { color: '#FFFFFF', fontWeight: '700', fontSize: 15 } });
