import { router, useLocalSearchParams } from 'expo-router';
import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { ScreenContainer } from '@/components/screen-container';
import { haptic } from '@/lib/haptics';
import { carrySessionParams, type SessionFlowParams } from '@/lib/session-flow';
const prompts = ['Feel both feet supported by the floor.', 'Notice one thing you can see.', 'Notice one sound near you.', 'Take one slower breath than the last.'];
export default function GroundingScreen() { const params = useLocalSearchParams<SessionFlowParams>(); const sessionParams = carrySessionParams(params); const [index, setIndex] = useState(0); useEffect(() => { const timer = setInterval(() => setIndex((v) => (v + 1) % prompts.length), 4500); return () => clearInterval(timer); }, []); return <ScreenContainer edges={['top','bottom','left','right']} containerClassName="bg-[#F4F7F5]" className="px-5"><View style={styles.content}><View style={styles.orb}><View style={styles.orbInner} /></View><Text style={styles.eyebrow}>GROUNDING</Text><Text style={styles.heading}>Come back to this moment.</Text><Text style={styles.body}>Stimulation is stopped. There is nothing else you need to do right now.</Text>{params.scenarioName ? <Text style={styles.caseNote}>Training case · {params.scenarioName}</Text> : null}<View style={styles.prompt}><Text style={styles.promptNumber}>{String(index + 1).padStart(2, '0')}</Text><Text style={styles.promptText}>{prompts[index]}</Text></View><Pressable onPress={() => { haptic.light(); setIndex((v) => (v + 1) % prompts.length); }} style={styles.button}><Text style={styles.buttonText}>Next grounding cue</Text></Pressable><Pressable onPress={() => router.push({ pathname: '/session/closure', params: sessionParams as Record<string, string> })}><Text style={styles.end}>End safely</Text></Pressable></View></ScreenContainer>; }
const styles = StyleSheet.create({ content: { flex: 1, justifyContent: 'center', gap: 16 }, orb: { width: 104, height: 104, borderRadius: 52, backgroundColor: '#DCEBE5', alignItems: 'center', justifyContent: 'center', alignSelf: 'center', marginBottom: 10 }, orbInner: { width: 54, height: 54, borderRadius: 27, backgroundColor: '#B8D8D2' }, eyebrow: { color: '#2F6F68', fontSize: 12, letterSpacing: 1.5, fontWeight: '700', textAlign: 'center' }, heading: { color: '#16252D', fontSize: 31, lineHeight: 37, fontWeight: '700', textAlign: 'center', letterSpacing: -0.6 }, body: { color: '#60716F', fontSize: 15, lineHeight: 22, textAlign: 'center' }, prompt: { backgroundColor: '#FFFFFF', borderRadius: 20, borderWidth: 1, borderColor: '#D9E2DE', padding: 20, minHeight: 118, justifyContent: 'center', marginTop: 8 }, promptNumber: { color: '#2F6F68', fontSize: 12, fontWeight: '700', letterSpacing: 1, marginBottom: 8 }, promptText: { color: '#16252D', fontSize: 19, lineHeight: 26, fontWeight: '600' }, button: { backgroundColor: '#2F6F68', alignItems: 'center', borderRadius: 15, paddingVertical: 16, marginTop: 8 }, buttonText: { color: '#FFFFFF', fontSize: 15, fontWeight: '700' }, caseNote: { color: '#2F6F68', textAlign: 'center', fontSize: 12, fontWeight: '700' }, end: { color: '#60716F', textAlign: 'center', fontSize: 14, fontWeight: '700', padding: 8 } });
