import AsyncStorage from '@react-native-async-storage/async-storage';
import type { SessionTelemetry, TelemetryEvent } from './telemetry';
import type { SubscriptionTier } from './monetization';

export type BlsMode = 'visual' | 'audio' | 'haptic' | 'mixed';
export type SessionSummary = { id: string; createdAt: string; durationMinutes: number; mode: BlsMode; initialSud: number; finalSud: number; reflection?: string };
export type JournalEntry = { id: string; createdAt: string; text: string };
export type BreathingPractice = { id: string; createdAt: string; rounds: number; durationSeconds: number };
const SESSION_KEY = 'emdr.session.summaries.v1';
const JOURNAL_KEY = 'emdr.journal.entries.v1';
const PREFERENCES_KEY = 'emdr.preferences.v1';
const SAFETY_PLAN_KEY = 'emdr.safety-plan.v1';
const BREATHING_KEY = 'emdr.breathing.practice.v1';
const TELEMETRY_KEY = 'emdr.telemetry';
const RECOVERY_AUDIT_KEY = 'emdr.recovery-audit.v1';
export type LocalStorageFailureMode = 'read' | 'write' | 'remove' | 'all' | null;
let localStorageFailureMode: LocalStorageFailureMode = null;
/** Test-only hook; production callers should leave this unset. */
export function setLocalStorageFailureMode(mode: LocalStorageFailureMode): void { localStorageFailureMode = mode; }
export type BlsAudioVolumePreference = 0.25 | 0.45 | 0.65;
export type BlsSoundscapePreference = 'none' | 'rain' | 'hum';
export type ExperiencePreferences = { onboardingComplete: boolean; haptics: boolean; reducedMotion: boolean; previewSubscriptionTier?: SubscriptionTier; blsAudioVolume?: BlsAudioVolumePreference; blsSoundscape?: BlsSoundscapePreference; lastStereoFeedback?: 'clear' | 'unclear' };
export type SafetyPlan = { trustedContactName?: string; trustedContactPhone?: string; copingNote?: string; updatedAt: string };
const DEFAULT_PREFERENCES: ExperiencePreferences = { onboardingComplete: false, haptics: true, reducedMotion: false, previewSubscriptionTier: 'free', blsAudioVolume: 0.45, blsSoundscape: 'none' };
function isRecord(value: unknown): value is Record<string, unknown> { return typeof value === 'object' && value !== null && !Array.isArray(value); }
function normalizePreferences(value: unknown): ExperiencePreferences {
  if (!isRecord(value)) return { ...DEFAULT_PREFERENCES };
  return {
    ...DEFAULT_PREFERENCES,
    onboardingComplete: typeof value.onboardingComplete === 'boolean' ? value.onboardingComplete : DEFAULT_PREFERENCES.onboardingComplete,
    haptics: typeof value.haptics === 'boolean' ? value.haptics : DEFAULT_PREFERENCES.haptics,
    reducedMotion: typeof value.reducedMotion === 'boolean' ? value.reducedMotion : DEFAULT_PREFERENCES.reducedMotion,
    previewSubscriptionTier: value.previewSubscriptionTier === 'free' || value.previewSubscriptionTier === 'basic' || value.previewSubscriptionTier === 'professional' || value.previewSubscriptionTier === 'enterprise' ? value.previewSubscriptionTier : DEFAULT_PREFERENCES.previewSubscriptionTier,
    blsAudioVolume: value.blsAudioVolume === 0.25 || value.blsAudioVolume === 0.45 || value.blsAudioVolume === 0.65 ? value.blsAudioVolume : DEFAULT_PREFERENCES.blsAudioVolume,
    blsSoundscape: value.blsSoundscape === 'none' || value.blsSoundscape === 'rain' || value.blsSoundscape === 'hum' ? value.blsSoundscape : DEFAULT_PREFERENCES.blsSoundscape,
    ...(value.lastStereoFeedback === 'clear' || value.lastStereoFeedback === 'unclear' ? { lastStereoFeedback: value.lastStereoFeedback } : {}),
  };
}
async function readJson<T>(key: string, fallback: T): Promise<T> { try { if (localStorageFailureMode === 'read' || localStorageFailureMode === 'all') throw new Error('simulated local read failure'); const raw = await AsyncStorage.getItem(key); return raw ? (JSON.parse(raw) as T) : fallback; } catch (error) { console.warn(`[local-storage] read failed for ${key}`, error); return fallback; } }
async function readJsonWithStatus<T>(key: string, fallback: T): Promise<{ value: T; usedFallback: boolean }> { try { if (localStorageFailureMode === 'read' || localStorageFailureMode === 'all') throw new Error('simulated local read failure'); const raw = await AsyncStorage.getItem(key); return raw ? { value: JSON.parse(raw) as T, usedFallback: false } : { value: fallback, usedFallback: false }; } catch (error) { console.warn(`[local-storage] fallback read used for ${key}`, error); return { value: fallback, usedFallback: true }; } }
function isFiniteNumber(value: unknown): value is number { return typeof value === 'number' && Number.isFinite(value); }
function isSessionSummary(value: unknown): value is SessionSummary { return isRecord(value) && typeof value.id === 'string' && typeof value.createdAt === 'string' && isFiniteNumber(value.durationMinutes) && (value.mode === 'visual' || value.mode === 'audio' || value.mode === 'haptic' || value.mode === 'mixed') && isFiniteNumber(value.initialSud) && isFiniteNumber(value.finalSud); }
function isJournalEntry(value: unknown): value is JournalEntry { return isRecord(value) && typeof value.id === 'string' && typeof value.createdAt === 'string' && typeof value.text === 'string'; }
function isBreathingPractice(value: unknown): value is BreathingPractice { return isRecord(value) && typeof value.id === 'string' && typeof value.createdAt === 'string' && isFiniteNumber(value.rounds) && isFiniteNumber(value.durationSeconds); }
function isTelemetryEvent(value: unknown): value is TelemetryEvent { return isRecord(value) && typeof value.id === 'string' && typeof value.createdAt === 'string' && (value.type === 'set-started' || value.type === 'set-paused' || value.type === 'set-stopped' || value.type === 'sud-recorded' || value.type === 'supervisor-cue' || value.type === 'recovery-resumed' || value.type === 'recovery-discarded') && typeof value.phase === 'string' && (value.value === undefined || isFiniteNumber(value.value)) && (value.note === undefined || typeof value.note === 'string'); }
function isSafetyPlan(value: unknown): value is SafetyPlan { return isRecord(value) && typeof value.updatedAt === 'string' && (value.trustedContactName === undefined || typeof value.trustedContactName === 'string') && (value.trustedContactPhone === undefined || typeof value.trustedContactPhone === 'string') && (value.copingNote === undefined || typeof value.copingNote === 'string'); }
function isSessionTelemetry(value: unknown): value is SessionTelemetry { return isRecord(value) && typeof value.sessionId === 'string' && typeof value.scenarioId === 'string' && typeof value.startedAt === 'string' && isFiniteNumber(value.sets) && isFiniteNumber(value.pauses) && Array.isArray(value.events) && value.events.every(isTelemetryEvent); }
function isRecoveryAuditEvent(value: unknown): value is RecoveryAuditEvent { return isRecord(value) && typeof value.id === 'string' && typeof value.sessionId === 'string' && (value.action === 'resumed' || value.action === 'discarded') && typeof value.createdAt === 'string'; }
async function readArray<T>(key: string, isItem: (value: unknown) => value is T): Promise<T[]> { const value = await readJson<unknown>(key, []); return Array.isArray(value) ? value.filter(isItem) : []; }
async function readArrayWithStatus<T>(key: string, isItem: (value: unknown) => value is T): Promise<{ value: T[]; usedFallback: boolean }> { const result = await readJsonWithStatus<unknown>(key, []); const raw = result.value as unknown; const validList = Array.isArray(raw); const value = validList ? raw.filter(isItem) : []; return { value, usedFallback: result.usedFallback || !validList || (validList && value.length !== raw.length) }; }
async function readSafetyPlanWithStatus(): Promise<{ value: SafetyPlan | null; usedFallback: boolean }> { const result = await readJsonWithStatus<unknown>(SAFETY_PLAN_KEY, null); const value = isSafetyPlan(result.value) ? result.value : null; return { value, usedFallback: result.usedFallback || (result.value !== null && value === null) }; }
async function writeJson(key: string, value: unknown): Promise<boolean> { try { if (localStorageFailureMode === 'write' || localStorageFailureMode === 'all') throw new Error('simulated local write failure'); await AsyncStorage.setItem(key, JSON.stringify(value)); return true; } catch (error) { console.warn(`[local-storage] write failed for ${key}`, error); return false; } }
async function removeKey(key: string): Promise<boolean> { try { if (localStorageFailureMode === 'remove' || localStorageFailureMode === 'all') throw new Error('simulated local remove failure'); await AsyncStorage.removeItem(key); return true; } catch (error) { console.warn(`[local-storage] remove failed for ${key}`, error); return false; } }
export async function getSessions(): Promise<SessionSummary[]> { return readArray<SessionSummary>(SESSION_KEY, isSessionSummary); }
export async function getSessionsWithStatus(): Promise<{ sessions: SessionSummary[]; usedFallback: boolean }> { const result = await readArrayWithStatus<SessionSummary>(SESSION_KEY, isSessionSummary); return { sessions: result.value, usedFallback: result.usedFallback }; }
export async function getTelemetry(): Promise<SessionTelemetry[]> { return readArray<SessionTelemetry>(TELEMETRY_KEY, isSessionTelemetry); }
export async function getInterruptedTelemetry(): Promise<SessionTelemetry | null> { const records = await getTelemetry(); return records.find((item) => !item.endedAt && item.events.at(-1)?.type !== 'set-stopped') ?? null; }
export async function saveTelemetry(telemetry: SessionTelemetry): Promise<boolean> { const existing = await getTelemetry(); return writeJson(TELEMETRY_KEY, [telemetry, ...existing.filter((item) => item.sessionId !== telemetry.sessionId)].slice(0, 25)); }
export async function updateTelemetryProgress(sessionId: string, patch: Partial<Pick<SessionTelemetry, 'mode' | 'audioOn' | 'hapticsOn' | 'speed' | 'durationMinutes' | 'elapsedSeconds' | 'scenarioName'>>): Promise<boolean> { const current = (await getTelemetry()).find((item) => item.sessionId === sessionId); return current ? saveTelemetry({ ...current, ...patch }) : false; }
export type RecoveryAuditEvent = { id: string; sessionId: string; action: 'resumed' | 'discarded'; createdAt: string; }
export async function getRecoveryAudit(): Promise<RecoveryAuditEvent[]> { return readArray<RecoveryAuditEvent>(RECOVERY_AUDIT_KEY, isRecoveryAuditEvent); }
export async function getRecoveryAuditWithStatus(): Promise<{ events: RecoveryAuditEvent[]; usedFallback: boolean }> { const result = await readArrayWithStatus<RecoveryAuditEvent>(RECOVERY_AUDIT_KEY, isRecoveryAuditEvent); return { events: result.value, usedFallback: result.usedFallback }; }
export async function saveRecoveryAudit(event: RecoveryAuditEvent): Promise<boolean> { try { if (localStorageFailureMode === 'write' || localStorageFailureMode === 'all') throw new Error('simulated local write failure'); const existing = await getRecoveryAudit(); await AsyncStorage.setItem(RECOVERY_AUDIT_KEY, JSON.stringify([event, ...existing].slice(0, 50))); return true; } catch (error) { console.warn('[local-storage] recovery audit save failed', error); return false; } }
export async function clearRecoveryAudit(): Promise<boolean> { return removeKey(RECOVERY_AUDIT_KEY); }
export async function discardTelemetry(sessionId: string): Promise<boolean> { try { if (localStorageFailureMode === 'write' || localStorageFailureMode === 'all') throw new Error('simulated local write failure'); const existing = await getTelemetry(); await AsyncStorage.setItem(TELEMETRY_KEY, JSON.stringify(existing.filter((item) => item.sessionId !== sessionId))); return true; } catch (error) { console.warn('[local-storage] telemetry discard failed', error); return false; } }
export async function appendTelemetryEvent(sessionId: string, event: TelemetryEvent): Promise<boolean> { const existing = await getTelemetry(); const current = existing.find((item) => item.sessionId === sessionId); if (!current) return false; current.events = [...current.events, event]; if (event.type === 'set-started') current.sets += 1; if (event.type === 'set-paused') current.pauses += 1; if (event.type === 'sud-recorded' && event.value !== undefined) current.finalSud = event.value; if (event.type === 'set-stopped') current.endedAt = event.createdAt; return saveTelemetry(current); }
export async function saveSession(session: SessionSummary): Promise<boolean> { try { if (localStorageFailureMode === 'write' || localStorageFailureMode === 'all') throw new Error('simulated local write failure'); const existing = await getSessions(); await AsyncStorage.setItem(SESSION_KEY, JSON.stringify([session, ...existing].slice(0, 50))); return true; } catch (error) { console.warn('[local-storage] session save failed', error); return false; } }
export async function getJournalEntries(): Promise<JournalEntry[]> { return readArray<JournalEntry>(JOURNAL_KEY, isJournalEntry); }
export async function getJournalEntriesWithStatus(): Promise<{ entries: JournalEntry[]; usedFallback: boolean }> { const result = await readArrayWithStatus<JournalEntry>(JOURNAL_KEY, isJournalEntry); return { entries: result.value, usedFallback: result.usedFallback }; }
export async function saveJournalEntry(text: string): Promise<JournalEntry | null> { const entry = { id: `journal_${Date.now()}`, createdAt: new Date().toISOString(), text }; const existing = await getJournalEntries(); const saved = await writeJson(JOURNAL_KEY, [entry, ...existing].slice(0, 50)); return saved ? entry : null; }
export async function getBreathingPractices(): Promise<BreathingPractice[]> { return readArray<BreathingPractice>(BREATHING_KEY, isBreathingPractice); }
export async function getProgressActivity(): Promise<{ sessions: SessionSummary[]; breathing: BreathingPractice[]; usedFallback: boolean }> { const [sessions, breathing] = await Promise.all([readArrayWithStatus<SessionSummary>(SESSION_KEY, isSessionSummary), readArrayWithStatus<BreathingPractice>(BREATHING_KEY, isBreathingPractice)]); return { sessions: sessions.value, breathing: breathing.value, usedFallback: sessions.usedFallback || breathing.usedFallback }; }
export async function saveBreathingPractice(rounds: number, durationSeconds: number): Promise<BreathingPractice | null> { const practice = { id: `breath_${Date.now()}`, createdAt: new Date().toISOString(), rounds, durationSeconds }; const existing = await getBreathingPractices(); const saved = await writeJson(BREATHING_KEY, [practice, ...existing].slice(0, 50)); return saved ? practice : null; }
export async function getPreferences(): Promise<ExperiencePreferences> { return normalizePreferences(await readJson<unknown>(PREFERENCES_KEY, DEFAULT_PREFERENCES)); }
export async function savePreferences(patch: Partial<ExperiencePreferences>): Promise<ExperiencePreferences | null> { const next = normalizePreferences({ ...(await getPreferences()), ...patch }); const saved = await writeJson(PREFERENCES_KEY, next); return saved ? next : null; }
export async function getSafetyPlan(): Promise<SafetyPlan | null> { const value = await readJson<unknown>(SAFETY_PLAN_KEY, null); return isSafetyPlan(value) ? value : null; }
export async function getSafetyPlanWithStatus(): Promise<{ plan: SafetyPlan | null; usedFallback: boolean }> { const result = await readSafetyPlanWithStatus(); return { plan: result.value, usedFallback: result.usedFallback }; }
export async function saveSafetyPlan(plan: Omit<SafetyPlan, 'updatedAt'>): Promise<SafetyPlan | null> { const next = { ...plan, updatedAt: new Date().toISOString() }; const saved = await writeJson(SAFETY_PLAN_KEY, next); return saved ? next : null; }
export async function getLocalDataExport() { const [sessions, journal, breathing, preferences, safetyPlan, telemetry, recoveryAudit] = await Promise.all([getSessions(), getJournalEntries(), getBreathingPractices(), getPreferences(), getSafetyPlan(), getTelemetry(), getRecoveryAudit()]); return { exportedAt: new Date().toISOString(), sessions, journal, breathing, preferences, safetyPlan, telemetry, recoveryAudit }; }
export async function getLocalDataExportWithStatus() { const [sessions, journal, breathing, preferences, safetyPlan, telemetry, recoveryAudit] = await Promise.all([readArrayWithStatus<SessionSummary>(SESSION_KEY, isSessionSummary), readArrayWithStatus<JournalEntry>(JOURNAL_KEY, isJournalEntry), readArrayWithStatus<BreathingPractice>(BREATHING_KEY, isBreathingPractice), readJsonWithStatus<unknown>(PREFERENCES_KEY, DEFAULT_PREFERENCES), readSafetyPlanWithStatus(), readArrayWithStatus<SessionTelemetry>(TELEMETRY_KEY, isSessionTelemetry), readArrayWithStatus<RecoveryAuditEvent>(RECOVERY_AUDIT_KEY, isRecoveryAuditEvent) ]); return { exportedAt: new Date().toISOString(), sessions: sessions.value, journal: journal.value, breathing: breathing.value, preferences: normalizePreferences(preferences.value), safetyPlan: safetyPlan.value, telemetry: telemetry.value, recoveryAudit: recoveryAudit.value, usedFallback: sessions.usedFallback || journal.usedFallback || breathing.usedFallback || preferences.usedFallback || safetyPlan.usedFallback || telemetry.usedFallback || recoveryAudit.usedFallback }; }
export async function clearAllLocalData(): Promise<boolean> { try { if (localStorageFailureMode === 'remove' || localStorageFailureMode === 'all') throw new Error('simulated local clear failure'); await AsyncStorage.multiRemove([SESSION_KEY, JOURNAL_KEY, PREFERENCES_KEY, SAFETY_PLAN_KEY, BREATHING_KEY, TELEMETRY_KEY, RECOVERY_AUDIT_KEY]); return true; } catch (error) { console.warn('[local-storage] clear all failed', error); return false; } }
export async function clearSessions(): Promise<boolean> { return removeKey(SESSION_KEY); }
